version: '3.7'
services:
  spark:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: sparkWorker1
    environment:
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_LOG: /spark/logs
      SPARK_MASTER: "spark://spark-master:7077"
    command: ["/bin/bash", "/worker.sh"]
    volumes:
      - ./worker.sh:/worker.sh
    ports:
      - "8081:8081"
    networks:
      - spark-network
    external_links:
      - spark-master
    restart: always

networks:
  spark-network:
    external: true
